development:
  adapter: mysql2
  encoding: utf8
  database: vt14
  username: root
  password:  
  host: localhost
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: vt14
  username: root
  password:  
  host: localhost
  port: 3306